### ISSUE TITLE
[ERROR]: gen failed with: 请登录...

### ISSUE THREAD

**Issue by jrackTao** [gogoyqj/sm2tsservice#12]
命令行输入：sm2tsservice --clear

提示：[ERROR]: gen failed with: 请登录...

**Comment by gogoyqj** [comment]
还是补充一下，一定要使用较新的 yapi 版本，且系统上清楚写着，可以通过 sm2tservice 生成代码的版本，才可以使用本工具 - 不然就需要自己手动实现 yapi 导出 json 数据的 接口

**Comment by jrackTao** [comment]
已经解决了，使用yapi忘记添加token了，加上就好了。。多谢了
