### ISSUE TITLE
增量更新无法全选

### ISSUE THREAD

**Issue by huixisheng** [gogoyqj/sm2tsservice#16]
![image](https://user-images.githubusercontent.com/1518967/73589729-528fb180-4515-11ea-94a9-71d60aa6197c.png)

**Comment by gogoyqj** [comment]
0/0 - 从这个看，应该是前后没有差异，所以不能全选吧

**Comment by gogoyqj** [comment]
@huixisheng 但是，如果下边实际显示有差异，但是右上角显示的还是“0/0”，那应该就是一个 bug 了，麻烦确认一下，是否确实没有差异

**Comment by huixisheng** [comment]
内容应该是一样的，那首次我要怎么更新？

**Comment by gogoyqj** [comment]
点全选，确定就可以了——其实内容一样，不更新也可以

**Comment by gogoyqj** [comment]
@huixisheng 升级到 3.2.5
