### ISSUE TITLE
[New Featrue] 支持自定义 Header 字段生成参数可选

### ISSUE THREAD

**Issue by haitaodesign** [gogoyqj/sm2tsservice#18]
1. 看到之前版本是有源代码公开的
2. 现在不公开是为什么？

**Comment by gogoyqj** [comment]
@haitaodesign 现在代码是从另外一个仓库同步来的

https://github.com/gogoyqj/tkit/tree/master/packages/service/src

**Comment by haitaodesign** [comment]
> @haitaodesign 现在代码是从另外一个仓库同步来的
> 
> https://github.com/gogoyqj/tkit/tree/master/packages/service/src

收到，谢谢！

**Comment by haitaodesign** [comment]
@gogoyqj 请教你一个问题，我们的前端自定义的响应头（headers） `Authorization `，在代码自动生成的时候请求参数就必须有这个参数，为了不在参数里面生成这个参数（不需要），我做了如下操作：

https://github.com/haitaodesign/sm2tsservice/commit/8607d435032b4527b22544821e222ec0768ec7e2

这样处理并不是很好的解决办法，当时也没有找到合适的方式，不知道有什么便捷的方式解决这个问题

**Comment by gogoyqj** [comment]
建议先把 yapi json 下载到本地，移除auth字段，再传递给工具生成代码

**Comment by haitaodesign** [comment]
> 建议先把 yapi json 下载到本地，移除auth字段，再传递给工具生成代码

这就需要我单度写工具自动化这块的功能，有木有好的办法在工具层面解决掉这个问题

**Comment by gogoyqj** [comment]
@haitaodesign 我在 yapiconfig 里加一个钩子吧

**Comment by gogoyqj** [comment]
3.2.6+
https://gogoyqj.github.io/sm2tsservice/sm2tsservice#124-yapiconfig

**Comment by haitaodesign** [comment]
> 3.2.6+
> https://gogoyqj.github.io/sm2tsservice/sm2tsservice#124-yapiconfig

好的，感谢！
